model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[features]
web_search_request = true #https://developers.openai.com/codex/cli/features#web-search

[projects."/Users/twoode/CODE/Scripts/Dotfiles/dotfiles"]
trust_level = "trusted"

[projects."/Users/twoode/CODE/Scratch/playWithChatEnterprise"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
